# Form implementation generated from reading ui file 'c:\Users\lydia\Documents\GitHub\Computer_Aided_Diagnosis_For_Chest_Radiograph\Desktop\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 785)
        self.load_image = QtWidgets.QPushButton(parent=Form)
        self.load_image.setGeometry(QtCore.QRect(210, 30, 121, 51))
        self.load_image.setObjectName("load_image")
        self.predict_image = QtWidgets.QPushButton(parent=Form)
        self.predict_image.setGeometry(QtCore.QRect(360, 30, 121, 51))
        self.predict_image.setObjectName("predict_image")
        self.oriCXR = QtWidgets.QGraphicsView(parent=Form)
        self.oriCXR.setGeometry(QtCore.QRect(20, 100, 711, 671))
        self.oriCXR.setObjectName("oriCXR")
        self.result = QtWidgets.QLabel(parent=Form)
        self.result.setGeometry(QtCore.QRect(530, 40, 201, 21))
        self.result.setText("")
        self.result.setObjectName("result")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Pneumothorax CAD"))
        self.load_image.setText(_translate("Form", "Load CXR"))
        self.predict_image.setText(_translate("Form", "Predict CXR"))
